import { Product } from '../types';
import magsafeBatteryPackImg from '../assets/images/magsafe_battery_pack_1788756906804.jpg';
import redmiCandyCaseImg from '../assets/images/redmi_candy_case_1788757243098.jpg';

export const HOT_DEAL_PRODUCT: Product = {
  id: 'hot-deal-1',
  category: 'power',
  categoryLabel: 'MAGSAFE CHARGING DOCKS',
  title: '3-in-1 Foldable MagSafe 15W Station',
  tag: 'Foldable 15W',
  badge: '-35% OFF',
  badgeColor: 'blue',
  rating: 4.9,
  soldCount: 384,
  price: 6800,
  originalPrice: 10500,
  image: 'https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80',
  brand: 'MagCharge',
  inStock: true,
  compatibleModels: ['iPhone 12 to 16 Pro Max', 'Apple Watch Ultra/Series 9/8', 'AirPods Pro/3', 'Qi2 Android Phones'],
  specs: ['15W MagSafe Fast Induction', 'Foldable Travel Aluminum Alloy Body', 'Over-Heat & Voltage Surge Shield', 'Type-C PD Cable Included'],
  warranty: '6 Months Official Store Warranty',
};

export const PRODUCTS: Product[] = [
  // ==================== PHONE BACK COVERS (COVERS) ====================
  {
    id: 'cover-1',
    category: 'covers',
    categoryLabel: 'APPLE SERIES',
    title: 'Magnetic Armor Frosted Matte Case with Camera Guard',
    tag: 'IP 15 Pro Max',
    badge: '-26%',
    badgeColor: 'red',
    rating: 4.9,
    soldCount: 142,
    price: 1850,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1601593346740-925612772716?auto=format&fit=crop&w=800&q=80',
    brand: 'Apple',
    inStock: true,
    compatibleModels: ['iPhone 15 Pro Max', 'iPhone 15 Pro', 'iPhone 15', 'iPhone 14 Pro Max', 'iPhone 13 Pro Max'],
    specs: ['Strong N52 Neodymium MagSafe Ring', 'Raised 1.8mm CNC Aluminum Camera Lip', 'Oleophobic Anti-Fingerprint Frosted Back', 'Drop Tested 10ft Military Spec'],
    warranty: '6 Months Replacement Warranty',
  },
  {
    id: 'cover-2',
    category: 'covers',
    categoryLabel: 'SAMSUNG GALAXY',
    title: 'Crystal Clear Anti-Yellowing Slim Cover (Air Cushion)',
    tag: 'S24 Ultra',
    badge: 'BESTSELLER',
    badgeColor: 'amber',
    rating: 4.8,
    soldCount: 310,
    price: 1450,
    originalPrice: 2200,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    brand: 'Samsung',
    inStock: true,
    compatibleModels: ['Galaxy S24 Ultra', 'Galaxy S24 Plus', 'Galaxy S24', 'Galaxy S23 Ultra', 'Galaxy S22 Ultra'],
    specs: ['Bayer German TPU Anti-Yellowing Matrix', '4-Corner Air Cushion Shock Pockets', 'Optical Dot Pattern (Zero Wet Look)', 'Wireless Fast Charging Friendly'],
    warranty: '6 Months Anti-Discoloration Warranty',
  },
  {
    id: 'cover-3',
    category: 'covers',
    categoryLabel: 'HEAVY ARMOR',
    title: 'Carbon Fiber Shockproof Rugged Bumper Case',
    tag: 'iPhone 14',
    badge: 'RUGGED',
    badgeColor: 'blue',
    rating: 5.0,
    soldCount: 88,
    price: 2200,
    originalPrice: 3100,
    image: 'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&w=800&q=80',
    brand: 'Spigen/UAG Style',
    inStock: true,
    compatibleModels: ['iPhone 14 Pro', 'iPhone 14', 'iPhone 14 Plus', 'iPhone 13', 'iPhone 12'],
    specs: ['Genuine Textured Carbon Fiber Inlay', 'Dual-Layer TPU + Polycarbonate Shell', 'Tactile Textured Side Grips', 'Meets MIL-STD-810G Drop Standards'],
    warranty: '6 Months Structural Warranty',
  },
  {
    id: 'cover-4',
    category: 'covers',
    categoryLabel: 'LEATHER FOLIO',
    title: 'Luxury Leather Wallet Case with RFID Card Slot',
    tag: 'Galaxy S23',
    badge: 'PREMIUM',
    badgeColor: 'blue',
    rating: 4.7,
    soldCount: 65,
    price: 2650,
    originalPrice: 3800,
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
    brand: 'Samsung',
    inStock: true,
    compatibleModels: ['Galaxy S23 Ultra', 'Galaxy S23', 'Galaxy S22', 'iPhone 15 Pro', 'iPhone 14'],
    specs: ['Handcrafted PU Saddle Leather', '3x RFID Blocking Card Slots + Cash Sleeve', 'Magnetic Clasp Kickstand Function', 'Internal Soft Microfiber Lining'],
    warranty: '6 Months Stitching & Leather Guarantee',
  },
  {
    id: 'cover-5',
    category: 'covers',
    categoryLabel: 'XIAOMI / REDMI',
    title: 'Electroplated Soft Silicone Slim Candy Case',
    tag: 'Redmi Note 13',
    badge: 'TRENDING',
    badgeColor: 'amber',
    rating: 4.8,
    soldCount: 214,
    price: 1250,
    originalPrice: 1900,
    image: redmiCandyCaseImg,
    brand: 'Xiaomi',
    inStock: true,
    compatibleModels: ['Redmi Note 13 Pro+ 5G', 'Redmi Note 13 Pro', 'Redmi Note 13 4G', 'Redmi Note 12', 'Poco X6 Pro'],
    specs: ['Laser Electroplated Rose Gold Edges', 'Baby-Skin Liquid Silicone Finish', 'Full Coverage Lens Hole Protection', 'Washable & Sweat Resistant'],
    warranty: '30-Day Guarantee',
  },
  // Extra covers for pagination & filtering
  {
    id: 'cover-6',
    category: 'covers',
    categoryLabel: 'APPLE SERIES',
    title: 'Silicone Soft-Touch Magnetic Case with Microfiber Inner',
    tag: 'iPhone 16 Pro',
    badge: 'NEW',
    badgeColor: 'blue',
    rating: 4.9,
    soldCount: 96,
    price: 1950,
    originalPrice: 2600,
    image: 'https://images.unsplash.com/photo-1616348436168-de43ad0db179?auto=format&fit=crop&w=800&q=80',
    brand: 'Apple',
    inStock: true,
    compatibleModels: ['iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16', 'iPhone 15'],
    specs: ['Silky Liquid Silicone Exterior', 'Microfiber Interior Scuff Protection', 'Built-in Powerful MagSafe Ring', 'Dust Repellent Coating'],
    warranty: '6 Months Warranty',
  },
  {
    id: 'cover-7',
    category: 'covers',
    categoryLabel: 'ONEPLUS / PIXEL',
    title: 'Sandstone Grippy Minimalist Hybrid Case',
    tag: 'Pixel 8 Pro',
    badge: 'POPULAR',
    badgeColor: 'amber',
    rating: 4.8,
    soldCount: 78,
    price: 1650,
    originalPrice: 2400,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    brand: 'Pixel/OnePlus',
    inStock: true,
    compatibleModels: ['Google Pixel 8 Pro', 'Google Pixel 8', 'Pixel 7A', 'OnePlus 12', 'OnePlus 11'],
    specs: ['Textured Sandstone Anti-Slip Finish', 'Ultra-Slim 1.1mm Profile', 'Precision CNC Camera Island Cutout', 'Wireless Fast Charge Support'],
    warranty: '6 Months Warranty',
  },

  // ==================== POWER BANKS & MAGSAFE (POWER) ====================
  {
    id: 'power-1',
    category: 'power',
    categoryLabel: 'LAPTOP & MOBILE',
    title: '20,000mAh 65W PD Fast Charging Bank with Digital Display',
    tag: '20,000mAh',
    badge: '65W PD',
    badgeColor: 'blue',
    rating: 4.9,
    soldCount: 278,
    price: 7450,
    originalPrice: 9900,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
    brand: 'Anker/Baseus',
    inStock: true,
    compatibleModels: ['MacBook Air/Pro', 'Dell XPS', 'iPhone 16/15/14', 'Samsung S24/S23', 'iPad Pro'],
    specs: ['65W Two-Way Type-C PD Fast Charge', 'Real-Time Smart LED Battery & Wattage Display', 'Charge MacBook Air to 50% in 35 mins', 'Airline Flight Safe Certified (74Wh)'],
    warranty: '6 Months Direct Replacement Warranty',
  },
  {
    id: 'power-2',
    category: 'power',
    categoryLabel: 'MAGSAFE WIRELESS',
    title: '10,000mAh MagSafe Ultra-Slim Magnetic Wireless Battery Pack',
    tag: '15W Qi',
    badge: 'MAGSAFE',
    badgeColor: 'blue',
    rating: 4.8,
    soldCount: 195,
    price: 5900,
    originalPrice: 7800,
    image: magsafeBatteryPackImg,
    brand: 'Apple/Joyroom',
    inStock: true,
    compatibleModels: ['iPhone 12, 13, 14, 15, 16 Series', 'AirPods Pro 2/3', 'MagSafe Magnetic Cases'],
    specs: ['10,000mAh High-Density Polymer Core', '15W Fast Wireless + 20W Wired PD Type-C', 'Snap-on Strong Magnetic Alignment', 'Foldable Zinc Metal Kickstand'],
    warranty: '6 Months Direct Warranty',
  },
  {
    id: 'power-3',
    category: 'power',
    categoryLabel: 'BASEUS GAN',
    title: '100W GaN 4-Port Fast Desktop Charger (3x Type-C + 1x USB-A)',
    tag: '100W Fast',
    badge: 'GaN III Pro',
    badgeColor: 'amber',
    rating: 5.0,
    soldCount: 84,
    price: 8200,
    originalPrice: 11500,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    brand: 'Baseus',
    inStock: true,
    compatibleModels: ['MacBook Pro 16/14/13', 'iPhone, Galaxy, Pixel', 'Nintendo Switch, Steam Deck', 'Power Banks'],
    specs: ['Advanced Gallium Nitride (GaN 3 Pro)', 'Simultaneous 4-Device Intelligent Allocation', 'BPS 2.0 Dynamic Current Regulation', 'Compact 40% Smaller than Apple 96W'],
    warranty: '6 Months Official Store Warranty',
  },
  {
    id: 'power-4',
    category: 'power',
    categoryLabel: 'AUTOMOTIVE',
    title: '65W Dual Type-C Car Charger with Real-Time Voltage LED',
    tag: '65W Dual',
    badge: 'CAR TECH',
    badgeColor: 'blue',
    rating: 4.7,
    soldCount: 163,
    price: 2400,
    originalPrice: 3500,
    image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80',
    brand: 'Baseus',
    inStock: true,
    compatibleModels: ['12V-24V Car/SUV/Van Sockets', 'PD 3.0 & QC 4.0+ Mobile Devices', 'Tablets & Dashcams'],
    specs: ['Dual Independent Type-C + USB-A Ports', 'Blue LED Voltage Battery Health Monitor', 'Aluminum Alloy Heat Dissipation Body', 'Gold-Plated Shrapnel for Rugged Roads'],
    warranty: '6 Months Warranty',
  },
  {
    id: 'power-5',
    category: 'power',
    categoryLabel: 'CABLES & CORDS',
    title: 'Braided 240W Type-C to Type-C Ultra-Durable Silicone Cable (2m)',
    tag: '240W • 2m',
    badge: 'BESTSELLER',
    badgeColor: 'amber',
    rating: 4.9,
    soldCount: 512,
    price: 1250,
    originalPrice: 1800,
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&w=800&q=80',
    brand: 'Ugreen',
    inStock: true,
    compatibleModels: ['MacBook, iPad Pro', 'Samsung Galaxy 45W PPS', 'iPhone 15/16 Series', 'Android Fast Charge'],
    specs: ['E-Marker Intelligent Chip for Safe 48V/5A', '50,000+ Bend Tested Ballistic Nylon Braid', '480Mbps High-Speed Data Sync', '2m (6.6ft) Length with Leather Cable Strap'],
    warranty: '6 Months Replacement Warranty',
  },
  {
    id: 'power-6',
    category: 'power',
    categoryLabel: 'FAST ADAPTERS',
    title: '30W GaN Super Fast Mini Wall Charger with PPS Support',
    tag: '30W Mini',
    badge: 'FAST PD',
    badgeColor: 'blue',
    rating: 4.8,
    soldCount: 320,
    price: 2650,
    originalPrice: 3600,
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
    brand: 'Anker',
    inStock: true,
    compatibleModels: ['iPhone 16/15/14/13', 'iPad Mini/Air', 'Samsung Super Fast Charging', 'Pixel Phones'],
    specs: ['Miniature Coin-Sized GaN Architecture', '30W USB Power Delivery 3.0 PPS', 'Cold-Running Thermal Guard Tech', 'UK 3-Pin Foldable Prongs'],
    warranty: '6 Months Warranty',
  },

  // ==================== HEADPHONES & AUDIO (AUDIO) ====================
  {
    id: 'audio-1',
    category: 'audio',
    categoryLabel: 'TRUE WIRELESS',
    title: 'Pro Wireless ANC Active Noise Cancelling Earbuds with Spatial Sound',
    tag: 'ANC 42dB',
    badge: '-30%',
    badgeColor: 'red',
    rating: 4.9,
    soldCount: 340,
    price: 6950,
    originalPrice: 9900,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    brand: 'Soundcore',
    inStock: true,
    compatibleModels: ['iOS & Android Bluetooth 5.4', 'Laptops & Smart TVs', 'Apple Spatial Audio Compatible'],
    specs: ['Hybrid -42dB Active Noise Cancellation', 'Transparency Pass-Through Ambient Mode', '38 Hours Combined Battery Life', 'Wireless Qi Case + Fast Type-C'],
    warranty: '6 Months Direct Warranty',
  },
  {
    id: 'audio-2',
    category: 'audio',
    categoryLabel: 'OVER-EAR STUDIO',
    title: 'Deep Bass Over-Ear Bluetooth 5.4 Wireless Headphones (60h Battery)',
    tag: 'Studio Bass',
    badge: '60H BATTERY',
    badgeColor: 'amber',
    rating: 4.8,
    soldCount: 98,
    price: 9500,
    originalPrice: 13000,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    brand: 'JBL/Edifier Style',
    inStock: true,
    compatibleModels: ['Bluetooth 5.4 + 3.5mm AUX Wired Mode', 'PC/Mac Studio Production', 'Mobile Phones & Tablets'],
    specs: ['40mm Bio-Cellulose Dynamic Drivers', '60 Hours Non-Stop Continuous Playtime', 'Memory Foam Protein Leather Ear Cushions', 'Multi-Point Bluetooth Dual Pairing'],
    warranty: '6 Months Official Warranty',
  },
  {
    id: 'audio-3',
    category: 'audio',
    categoryLabel: 'RUNNING & GYM',
    title: 'Bone Conduction Open-Ear Sports Bluetooth Headset IPX8 Waterproof',
    tag: 'Open-Ear',
    badge: 'IPX8 SPORT',
    badgeColor: 'blue',
    rating: 4.7,
    soldCount: 72,
    price: 8200,
    originalPrice: 11200,
    image: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
    brand: 'SportTech',
    inStock: true,
    compatibleModels: ['Gym Runners, Cyclists, Swimming', 'iOS, Android & Smartwatches'],
    specs: ['True Bone Conduction Acoustic Vibration', 'IPX8 Waterproof & Sweatproof Rating', 'Titanium Memory Alloy Flexible Frame (28g)', 'Magnetic Quick Fast-Charging Dock'],
    warranty: '6 Months Warranty',
  },
  {
    id: 'audio-4',
    category: 'audio',
    categoryLabel: 'WIRED AUDIO',
    title: 'Hi-Fi Quad-Core Dual Driver Wired In-Ear Earphones with HD Mic',
    tag: '3.5mm / Type-C',
    badge: 'HI-FI DUAL',
    badgeColor: 'blue',
    rating: 4.8,
    soldCount: 480,
    price: 1450,
    originalPrice: 2100,
    image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    brand: 'KZ / QKZ',
    inStock: true,
    compatibleModels: ['3.5mm Jack & Type-C Digital Audio Adapters', 'Laptops, Gaming Controllers, Phones'],
    specs: ['Dual 10mm Graphene Composite Diaphragms', 'Lossless Oxygen-Free Copper Braided Wire', 'MEMS High Definition Noise-Cancelling Mic', 'Ergonomic 120° Angled Ear Tips'],
    warranty: '6 Months Replacement Warranty',
  },
  {
    id: 'audio-5',
    category: 'audio',
    categoryLabel: 'GAMING GEAR',
    title: 'Low-Latency Gaming TWS Earbuds with RGB Light & ENC Mic',
    tag: 'ENC Mic',
    badge: 'GAMING 40ms',
    badgeColor: 'red',
    rating: 4.9,
    soldCount: 230,
    price: 4800,
    originalPrice: 6500,
    image: 'https://images.unsplash.com/photo-1590658006821-04f4008d5717?auto=format&fit=crop&w=800&q=80',
    brand: 'CyberGear',
    inStock: true,
    compatibleModels: ['PUBG Mobile, Call of Duty, FreeFire', 'iOS & Android Gaming Devices'],
    specs: ['Ultra-Low 40ms Audio-Video Synchronization', 'RGB Futuristic Breathing LED Case', 'Dual ENC Mics for Crystal Clear Squad Chat', '13mm Bass-Boosted Drivers'],
    warranty: '6 Months Warranty',
  },
  {
    id: 'audio-6',
    category: 'audio',
    categoryLabel: 'TRUE WIRELESS',
    title: 'AirSound Pro Semi-In-Ear Ultra-Light Wireless Earphones',
    tag: 'BT 5.3',
    badge: 'BESTSELLER',
    badgeColor: 'amber',
    rating: 4.8,
    soldCount: 390,
    price: 3600,
    originalPrice: 4900,
    image: 'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80',
    brand: 'Soundcore',
    inStock: true,
    compatibleModels: ['All Bluetooth-enabled Phones', 'Laptops, Tablets'],
    specs: ['Half-In-Ear Pressure-Free Comfort (3.3g)', 'Clear Voice Calling with ENC Algorithm', '25 Hours Total Endurance with USB-C', 'Instant Open-Lid Auto Re-Connection'],
    warranty: '6 Months Warranty',
  },
];

export const DEMO_TRACKING: Record<string, any> = {
  '#ST-8821': {
    orderId: '#ST-8821',
    customerName: 'Kasun Ranmal',
    phone: '+94 77 *** 4567',
    destination: 'Maharagama / Colombo 05',
    estimatedDelivery: 'Tomorrow by 2:30 PM',
    courier: 'Domex Express Delivery (COD Verified)',
    status: 'Out for Delivery',
    total: 3300,
    items: [
      { name: 'Magnetic Armor Frosted Matte Case (IP 15 Pro Max)', qty: 1, price: 1850 },
      { name: 'Braided 240W Type-C to Type-C Cable (2m)', qty: 1, price: 1250 },
      { name: 'Islandwide COD Courier Fee', qty: 1, price: 200 },
    ],
    steps: [
      { title: 'Order Placed & Confirmed', location: 'Sakith Tech Web Desk', time: 'Yesterday, 10:15 AM', completed: true },
      { title: 'Item Inspected & Voltage Tested', location: 'Maharagama Fulfillment Hub', time: 'Yesterday, 02:45 PM', completed: true },
      { title: 'Handed to Courier Partner', location: 'Domex Hub Maharagama', time: 'Yesterday, 06:20 PM', completed: true },
      { title: 'Dispatched to Delivery Rider', location: 'Colombo City Hub (Domex Rider: #DX-412)', time: 'Today, 08:30 AM', completed: true, current: true },
      { title: 'Doorstep Handover & Payment Collection', location: 'Customer Destination', time: 'Estimated: Today, 02:30 PM', completed: false },
    ],
  },
  'DEFAULT': {
    orderId: '#ST-9042',
    customerName: 'Verified Customer',
    phone: '+94 7X XXX XXXX',
    destination: 'Colombo / Islandwide Doorstep',
    estimatedDelivery: 'Within 24-48 Hours',
    courier: 'Pronto / Domex Cash on Delivery',
    status: 'Dispatched',
    total: 4100,
    items: [
      { name: 'Crystal Clear Anti-Yellowing Slim Cover (S24 Ultra)', qty: 1, price: 1450 },
      { name: '65W Dual Type-C Car Charger with LED', qty: 1, price: 2400 },
      { name: 'Express Islandwide Courier', qty: 1, price: 250 },
    ],
    steps: [
      { title: 'Order Placed & Authenticated', location: 'Sakith Tech Online System', time: '09:00 AM', completed: true },
      { title: 'QC Verification & Tamper-Proof Seal Attached', location: 'Maharagama Tech Hub', time: '11:30 AM', completed: true },
      { title: 'Dispatched via Islandwide Courier', location: 'Central Sorting Hub', time: '03:15 PM', completed: true, current: true },
      { title: 'Arrival at Regional Distribution Facility', location: 'Your District Depot', time: 'Tomorrow, 08:00 AM', completed: false },
      { title: 'Doorstep Delivery with Cash On Delivery', location: 'Recipient Address', time: 'Tomorrow Afternoon', completed: false },
    ],
  },
};
